---
version: "3"

services:

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=121
      - TZ=America/Phoenix
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /srv/other/docker/fileshare/config-deluge:/config
      - /srv/media/Torrents/Deluge:/torrents
      - /srv/media/Torrents/Deluge:/srv/media/Torrents/Deluge
    ports:
      - 8112
      - 9893:9893
      - 9893:9893/udp
      - 58846:58846
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=121
      - TZ=America/Phoenix
    volumes:
      - /srv/other/docker/fileshare/config-sonarr:/config
      - /srv/media:/srv/media
    networks:
      - default
    ports:
      #- 8989:8989
      - 8989
    mem_limit: 4096m
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=121
      - TZ=America/Phoenix
    volumes:
      - /srv/other/docker/fileshare/config-radarr:/config
      - /srv/media:/srv/media
    ports:
      - 7878
    mem_limit: 4096m
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=121
      - TZ=America/Phoenix
    volumes:
      - /srv/other/docker/fileshare/config-jackett:/config
      - /srv/other/docker/downloads:/downloads
    networks:
      - default
    ports:
      - 9117:9117
    mem_limit: 4096m
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - TEST=ok
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - default
    ports:
      - 443:443
    restart: unless-stopped

networks:
  default:
    name: fileshare-network
