---
version: "3"

services:

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=121
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /srv/other/docker/fileshare/config-deluge:/config
      - ${DELUGE_DOWNLOAD_ROOT}:/torrents
      - ${DELUGE_DOWNLOAD_ROOT}:${DELUGE_DOWNLOAD_ROOT}
    ports:
      # - 8112
      - 9893:9893
      - 9893:9893/udp
      - 58846:58846
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=121
      - TZ=${TZ}
    volumes:
      - /srv/other/docker/fileshare/config-sonarr:/config
      - ${DELUGE_DOWNLOAD_ROOT}:${DELUGE_DOWNLOAD_ROOT}:rw
      - ${VIDEO_FILES}:${VIDEO_FILES}:rw
    networks:
      - default
    # ports:
    #  - 8989:8989
    mem_limit: 4096m
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=121
      - TZ=${TZ}
    volumes:
      - /srv/other/docker/fileshare/config-radarr:/config
      - ${DELUGE_DOWNLOAD_ROOT}:${DELUGE_DOWNLOAD_ROOT}:rw
      - ${VIDEO_FILES}:${VIDEO_FILES}:rw
      # ports:
      # - 7878
    mem_limit: 4096m
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=121
      - TZ=${TZ}
    volumes:
      - /srv/other/docker/fileshare/config-jackett:/config
    networks:
      - default
    # ports:
    #   - 9117
    mem_limit: 4096m
    restart: unless-stopped

  unpackerr:
    image: cr.hotio.dev/hotio/unpackerr
    container_name: unpackerr
    environment:
      - PUID=1000
      - PGID=121
      - UMASK=002
      - TZ=${TZ}
      - UN_SONARR_0_API_KEY=${UN_SONARR_0_API_KEY}
      - UN_SONARR_0_PATHS_0=${DELUGE_DOWNLOAD_ROOT}
      - UN_RADARR_0_API_KEY=${UN_RADARR_0_API_KEY}
      - UN_RADARR_0_PATHS_0=${DELUGE_DOWNLOAD_ROOT}
    volumes:
      - /srv/other/docker/fileshare/config-unpackerr:/config
      - ${DELUGE_DOWNLOAD_ROOT}:${DELUGE_DOWNLOAD_ROOT}:rw
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - TEST=ok
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - default
    ports:
      - 443:443
    restart: unless-stopped

networks:
  default:
    name: fileshare-network
